### PR TITLE
chg: replaced `transactions.getData` with `api.get`

### PR DESCRIPTION
**Pull request by twilson63**
When calling `transactions.getData` for some requests resulting in an errors, changed to `api.get` and the errors were resolved. 

According to Ros of Arweave, `api.get` will result in better performance because of caching.

I added some tests with uvu, nock, and tsm, happy to change the tests to whatever you prefer, just wanted to verify my code changes worked. Also, I could not get it to build because of TS errors, I am happy to resolve these, if you would prefer, but seems to be a lot of implicit any's.

Thank you in advance for reviewing this PR, happy to modify to meet your standards, just let me know.

Thx

Tom

### CODE REVIEW

**Comment by cromatikap** [comment]
Hi Tom, thanks a lot for contributing, that's awesome! 🥇 
Good idea to add tests 👍 

----

On this part:
```typescript
      // @ts-ignore
      let profile = (
        await this.arweave.api.get(txid).catch(() => {
          data: null;
        })
      ).data;
```
I guess you wanted the object { data: null } to be returned by the arrow function in the `catch()`. 
The brackets are considered to be the body of the function so in that case (if I'm not mistaken) `data` is a labeled statement and the function returns `void` :)

I modified it this way and no complain anymore from typescript:
```typescript
      let profile = (
        await this.arweave.api.get(txid).catch(() => {
          return { data: null };
        })
      ).data;
```

----

Concerning the second TS error: `Property 'owner' does not exist on type 'ArdbTransaction | ArdbBlock'.`

The following ternary condition fixed it:
```
const addr = 'owner' in tx ? tx.owner.address : 'anonymous';
```
In reality `owner` always come with a `tx` and I never witnessed an `'anonymous'` value.
Looking at `tx.owner.address` property is more reliable than `profile.addr`.

----

After that, I had errors with the imports of `arweave-account` from the Account app because of `"type": "module"` in `package.json`. I tweaked the `tsconfig.json` but I didn't find a satisfying solution. I'd rather keep it `"type": "commonjs"` but I'm open to suggestions.

**Comment by cromatikap** [comment]
Just added a commit, does it build for you?

**Comment by twilson63** [comment]
Thanks for looking through it, and catching some issues, I will give it a
spin

**Comment by twilson63** [comment]
ty for finding those things, I am cool with all of your suggestions, trying to build now.

**Pull request merged**
